org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# DISABLE JETIFIER: This stops Gradle from corrupting modern Firebase BoM structures!
android.enableJetifier=false

# BYPASS METADATA BLOCKS: Forces Gradle to pass the checkDebugAarMetadata task
android.disableDependencyMetadataCheck=true

# Force the Android build wrapper to strip out Impeller and use stable Skia
flutter.android.enableImpeller=false
org.flutter.egl=true